#!/usr/bin/bash

# Collect all data
# Generated by CEMAC (UoL) 2018
# This script will collect_all sensor data
#

# SET PATHS

# Where to store data
DATAPATH='../data/'
# Today
now=$(date +"%Y-%m-%dT%T")
# All stations and IDS
stationnames=("San_Ju" "El_Crucero" "San_Juan" "station_****" "Pacaya Rigoberto" "station_*****" "El_Panama")
stationIDs=("****" "****" "****" "*****" "*****" "***" "*****" "****")
# For each station run getAQ with corresponding ID
for i in ${!stationnames[*]};
  do
    fname=${stationnames[$i]}
    echo "Retriving ${stationnames[$i]} data"
    echo "running"
    echo "./getAQMeshData.py ${stationIDs[$i]} 2018-01-01T00:00:00 $now 'SO2 NO2' all"
    ./getAQMeshData.py ${stationIDs[$i]} 2018-01-01T00:00:00 $now 'SO2 NO2' all
    # If there was any data create a folder and put it there!
    if [ ! -e $DATAPATH$FNAME ];
    then
      mkdir $DATAPATH$FNAME
    fi
    files=( AQ*.csv )
    if [ -e $files ];
    then
      mv $files $DATAPATH$FNAME
    fi
done
